shell = require("shell")
shell.execute("rm GUI.lua")
shell.execute("rm POS.lua")
shell.execute("rm menu.json")
shell.execute("rm writer.lua")
shell.execute("rm json.lua")
shell.execute("wget https://raw.githubusercontent.com/EnragedStrings/OCBank/main/Register/GUI.lua")
shell.execute("wget https://raw.githubusercontent.com/EnragedStrings/OCBank/main/Register/POS.lua")
shell.execute("wget https://raw.githubusercontent.com/EnragedStrings/OCBank/main/Register/menu.json")
shell.execute("POS")
