shell = require("shell")
shell.execute("rm POS.lua")
shell.execute("rm menu.lua")
shell.execute("wget https://raw.githubusercontent.com/EnragedStrings/OCBank/main/Register/POS.lua")
shell.execute("wget https://raw.githubusercontent.com/EnragedStrings/OCBank/main/Register/menu.lua")
shell.execute("POS")
