shell = require("shell")
shell.execute("wget https://github.com/EnragedStrings/OCBank/blob/main/GUI.lua")
shell.execute("wget https://github.com/EnragedStrings/OCBank/blob/main/POS.lua")
shell.execute("wget https://github.com/EnragedStrings/OCBank/blob/main/menu.json")
shell.execute("wget https://github.com/EnragedStrings/OCBank/blob/main/writer.lua")